config:
  info: config-dev.yml version = 4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myr-code/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main

